export const ADD_NEW_DECK = 'ADD_NEW_DECK';
export const ADD_CARD_TO_CARDS = 'ADD_CARD_TO_CARDS';
export const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK';
export const RECEIVE_INITIAL_CARDS = 'RECEIVE_INITIAL_CARDS';
export const RECEIVE_INITIAL_DECKS = 'RECEIVE_INITIAL_DECKS';